config/routes.rb
Rails.application.routes.draw do

  resources :groups, shallow: true do
    # https://guides.rubyonrails.org/routing.html
    # this defines non-shallow routes that rely on group id such as new, create, create
    # the rest like show, edit, update, destroy are defined without group id since they are persisted in DB already
    resources :messages

    # we can do a third level nesting here so that a message belongs to message and then group
    # it is frowned upon due to level of nesting
    resources :group_users, except: %i[index show update edit]
  end

  # this expects a reply action in messages as reply_message_path
  resources :messages, only: [] do
    get 'reply', on: :member
  end

  devise_for :users

  # this would be useful if only current user can view their own profile
  # this will not need a user id
  resource :profile, only: %i[edit update show]
  resolve('Profile'){[:profile]}

  # make profiles publicly accessibly
  # this will need a user_id field
  resources :users do
     resource :profile, only: [ :show ]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get "/welcome", to: 'home#welcome'
  root "home#dashboard"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates_presence_of :content
  has_ancestry touch: true

  # we can trigger an event on messages that allows us to update a count/cache counter then fire an event when that changes
  # it ensures we don't send events on edit/update events for messages
  after_create_commit :broadcast_update


  # now that changing or creating a message will trigger an event here
  # we can stream updates via action cable

  # this will broadcast all events we send

  def broadcast_update
    # we can update the specific group using the dom_id
    # This is the same syntax used in controllers but now we need to create our own channels
    # we can send to group_id,

    # broadcast_update is fine but broadcast_update_later is recommended to avoid slow execution
    # syntax channel_id, partial, locals, target_to_update
    broadcast_replace_later_to("groups",  target: "group_#{group_id}", partial: "groups/group_preview", locals: { group:  group, current_user: user })

    # Now we also need to update the messages for those watching the channel
    # we are saying render the new message using the partial, then look for an id called messages in the dom and insert it at the end of that element while using the group_id channel to send this
    broadcast_append_later_to("groups", target: "messages", partial: "messages/message", locals: { message: self, current_user: user })
  end
  # message.broadcast_append_later_to("group_#{message.group_id}", partial: "messages/message", locals: { message: , current_user: message.user}, target: "messages")
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy reply]
  before_action :set_group, only: %i[new index create]

  # GET /messages or /messages.json
  def index
    @messages = if @group
     @group.messages
    else
      Message.all
    end
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    # here, we shall listen for the message id and use ancestry
    if params[:message_id]
       @parent = Message.find(params[:message_id])
       @message = @parent.children.new
    else
      @parent = nil
      @message = @group.messages.new
    end
  end

  # GET /messages/1/edit
  def edit
  end

  def reply
    @group = @message.group
    @message = @message.children.new(group: @group)
    # can we render a partial here instead of a full route??
    # we can deviate from defaults
    render 'messages/new'
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to root_path(current_id: @message.group), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to group_messages_path(@message.group), notice: "Message was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to group_messages_path(@message.group), notice: "Message was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def message_params
      # compact allows us to remove the group_id which is not present for update action
      params.expect(message: [:content, :ancestry]).merge({
         user_id: current_user.id, group_id: @group&.id
         }).compact_blank!
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<!--# at this point, the message will contain data about it's parent which we need to post/edit to-->
<%= form_with(model: [group, message], class: "flex items-center space-x-2 py-4 px-2 sm:px-4 bg-white border-t border-gray-200") do |form| %>
  <%= form.label :content, class: "sr-only" %>
  <div class="flex relative w-full">
    <%= form.text_area :content,
    rows: 3,
    placeholder: message.has_parent? ? "Reply to: #{message.parent.user.name}":  "Type a message...",
    class: "flex-grow resize-none rounded-2xl border-none p-3 text-sm focus:outline-none focus:ring-0 bg-gray-100"
  %>
    <%= link_to "X", new_group_message_path(group), class: " bg-accent px-2 rounded-lg absolute cursor-pointer left-1 -mt-2" if message.has_parent? %>
  </div>
  <%= form.text_field :ancestry, class: "hidden" %>
  <%= button_to type: "submit" do %>
    <div class="h-10 w-10 flex items-center justify-center rounded-full bg-accent hover:bg-blue-500 text-white cursor-pointer transition-all duration-200">
      <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 256 256">
        <path d="M227.32,28.68a16,16,0,0,0-15.66-4.08l-.15,0L19.57,82.84a16,16,0,0,0-2.49,29.8L102,154l41.3,84.87A15.86,15.86,0,0,0,157.74,248q.69,0,1.38-.06a15.88,15.88,0,0,0,14-11.51l58.2-191.94c0-.05,0-.1,0-.15A16,16,0,0,0,227.32,28.68ZM157.83,231.85l-.05.14,0-.07-40.06-82.3,48-48a8,8,0,0,0-11.31-11.31l-48,48L24.08,98.25l-.07,0,.14,0L216,40Z"></path>
      </svg>
    </div>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>" class="flex my-4 p-2 space-x-2 message <%= message.user == current_user ? 'justify-end' : ' justify-start' %> ">
  <% if message.user != current_user %>
    <%= image_tag message.user&.profile&.avatar.variant(:thumb).processed, class: "h-8 w-8 rounded-full object-cover flex-shrink-0" if message.user&.profile&.avatar&.attached? %>
  <% end %>
  <div class="group relative max-w-xs sm:max-w-sm px-4 py-2 text-base font-sans rounded-xl w-[80%]
    <%= 'bg-green-200 text-gray-800 rounded-tl-none' if message.user == current_user %>
    <%= 'bg-blue-200 text-gray-800 rounded-tl-none' unless message.user == current_user %>">
    <strong class="font-semibold text-xs mb-1 block">
      <%= message.user&.profile&.name %>
    </strong>
    <% if message.has_parent? %>
      <%= link_to "#message_#{message.parent.id}" do  %>
        <div class="opacity-80 bg-gray-100 border border-gray-200 p-2 rounded hover:opacity-90 my-1">
          <strong class="font-normal text-xs line-clamp-1 mb-1">
            <%= message.parent.user&.profile&.name %>
          </strong>
          <p class="leading-snug text-xs mb-1 line-clamp-1"><%= message.parent.content %></p>
        </div>
      <% end %>
    <% end %>
    <p class="leading-snug text-base mb-4"><%= message.content %></p>
    <div class="flex justify-end gap-2">
      <!-- # now that our links are running inside a frame called messages,
      Hotwire will try to look for a frame called messages on the target reply page and also the profile path
      We need to disable that-->
      <%# raise "hey" %>
      <%= link_to "Reply", reply_message_path(message), data: {turbo_frame: "new_message"}, class: 'text-sm text-gray-800  mt-2 px-2 py-1 opacity-0 transition-all duration-300 group-hover:opacity-100' %>
      <%= link_to "View Profile", user_profile_path(message.user), data: {turbo_frame: "_top"}, class: 'text-sm text-gray-800  mt-2 px-2 py-1 opacity-0 transition-all duration-300 group-hover:opacity-100' unless message.user == current_user %>
    </div>
    <div class="text-right text-xs mt-1 <%= 'text-gray-500' if message.user == current_user %> <%= 'text-gray-500' unless message.user == current_user %>">
      <%= message.created_at.strftime('%l:%M %P') %>
    </div>
  </div>
  <% if message.user == current_user %>
    <%= image_tag message.user&.profile&.avatar.variant(:thumb).processed, class: "h-8 w-8 rounded-full object-cover flex-shrink-0" if message.user&.profile&.avatar&.attached? %>
  <% end %>
</div>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to messages", group_messages_path(@message.group), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<% content_for :title, "Messages for" %>
<div class="w-full container">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Messages for `<%= @group.title %></h1>
    <%= link_to "New message", new_group_message_path(@group), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>
  <!--# use frames to decompose the page to enable caching, and deliver the via frames-->
  <%= turbo_frame_tag "messages", class: "min-w-full space-y-5 my-9" do %>
    <% if @messages.any? %>
      <%= render @messages %>
    <% else %>
      <p class="text-center my-10">No messages found.</p>
    <% end %>
  <% end %>
</div>

app/views/messages/new.html.erb
<% content_for :title, "New message for `#{@group.title}`" %>
<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl mb-8">New message for `<%= @group.title %></h1>
  <div class="my-6">
    <%= turbo_frame_tag "new_message" do %>
      <%= render "form", message: @message, group: @group, parent: @parent %>
    <% end %>
  </div>
  <%= link_to "Back to messages", group_messages_path(@group), class: "btn primary-btn" %>
</div>

app/views/messages/show.html.erb
<% content_for :title, "Showing message" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing message</h1>

  <%= render @message %>

  <%= link_to "Edit this message", edit_message_path(@message), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to messages", group_messages_path(@message.group), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this message", @message, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>