config/routes.rb
Rails.application.routes.draw do

  resources :groups, shallow: true do
    # https://guides.rubyonrails.org/routing.html
    # this defines non-shallow routes that rely on group id such as new, create, create
    # the rest like show, edit, update, destroy are defined without group id since they are persisted in DB already
    resources :messages

    # we can do a third level nesting here so that a message belongs to message and then group
    # it is frowned upon due to level of nesting
    resources :group_users, except: %i[index show update edit]
  end

  # this expects a reply action in messages as reply_message_path
  resources :messages, only: [] do
    get 'reply', on: :member
  end

  devise_for :users

  # this would be useful if only current user can view their own profile
  # this will not need a user id
  resource :profile, only: %i[edit update show]
  resolve('Profile'){[:profile]}

  # make profiles publicly accessibly
  # this will need a user_id field
  resources :users do
     resource :profile, only: [ :show ]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get "/welcome", to: 'home#welcome'
  root "home#dashboard"
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :group, uniqueness: { scope: :user }
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
  include Groupable
  before_action :set_group_user, only: %i[ edit destroy ]
  before_action :fetch_groups, only: :destroy

  # GET /group_users/new
  def new
    @group_user = GroupUser.new
  end

  # POST /group_users or /group_users.json
  def create
    @group_user = GroupUser.new(group_user_params)

    respond_to do |format|
      if @group_user.save
        format.html { redirect_to root_path(current_id: @group_user.group_id), notice: "You have joined the group!" }
        format.json { render :show, status: :created, location: @group_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_users/1 or /group_users/1.json
  def destroy
    @group_user.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "You have left the group!", status: :see_other }
      format.json { head :no_content }

      # here we need to define a turbo request
      # why?
      # because we need to move the group out of the member group and also revoke access to groups
      # we can stream a change to partials that will be affected

      # we need to ask ourselves what will change if we accessed the default page for this?
      # this a member group so we shall access it from group show path
      # losing access mean the button needs to change

      format.turbo_stream do
        # action, target, partial, locals is the pattern
        render turbo_stream: turbo_stream.update(:group, partial: "groups/group", locals: { group: @group_user.group }) +
        turbo_stream.replace(:current_group, partial: "home/main_content", locals: {current_group: @group_user.group}) +
        turbo_stream.replace(:sidebar_left, partial: "home/sidebar_left", locals: { other_groups: @other_groups, your_groups: @your_groups })

        # now we handle cases where this turbo frame might be reused like the dashboard page
        # if you leave a group, you can't see messages or even add a message option
        # we can chain turbo renders
      end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_user
      @group_user = GroupUser.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def group_user_params
      {
        user_id: current_user.id,
        group_id: params[:group_id]
      }
    end
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/views/group_users/_form.html.erb
<%= form_with(model: group_user, class: "contents") do |form| %>
  <% if group_user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(group_user.errors.count, "error") %> prohibited this group_user from being saved:</h2>

      <ul class="list-disc ml-6">
        <% group_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": group_user.errors[:user_id].none?, "border-red-400 focus:outline-red-600": group_user.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :group_id %>
    <%= form.text_field :group_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": group_user.errors[:group_id].none?, "border-red-400 focus:outline-red-600": group_user.errors[:group_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/group_users/_group_user.html.erb
<div id="<%= dom_id group_user %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= group_user.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Group:</strong>
    <%= group_user.group_id %>
  </div>
</div>

app/views/group_users/edit.html.erb
<% content_for :title, "Editing group user" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group user</h1>

  <%= render "form", group_user: @group_user %>

  <%= link_to "Show this group user", @group_user, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to group users", group_users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/group_users/index.html.erb
<% content_for :title, "Group users" %>

<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Group users</h1>
    <%= link_to "New group user", new_group_user_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="group_users" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @group_users.any? %>
      <% @group_users.each do |group_user| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render group_user %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", group_user, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_group_user_path(group_user), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", group_user, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No group users found.</p>
    <% end %>
  </div>
</div>

app/views/group_users/new.html.erb
<% content_for :title, "New group user" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group user</h1>

  <%= render "form", group_user: @group_user %>

  <%= link_to "Back to group users", group_users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/group_users/show.html.erb
<% content_for :title, "Showing group user" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing group user</h1>

  <%= render @group_user %>

  <%= link_to "Edit this group user", edit_group_user_path(@group_user), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to group users", group_users_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this group user", @group_user, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>