config/routes.rb
Rails.application.routes.draw do

  resources :groups, shallow: true do
    # https://guides.rubyonrails.org/routing.html
    # this defines non-shallow routes that rely on group id such as new, create, create
    # the rest like show, edit, update, destroy are defined without group id since they are persisted in DB already
    resources :messages

    # we can do a third level nesting here so that a message belongs to message and then group
    # it is frowned upon due to level of nesting
    resources :group_users, except: %i[index show update edit]
  end

  # this expects a reply action in messages as reply_message_path
  resources :messages, only: [] do
    get 'reply', on: :member
  end

  devise_for :users

  # this would be useful if only current user can view their own profile
  # this will not need a user id
  resource :profile, only: %i[edit update show]
  resolve('Profile'){[:profile]}

  # make profiles publicly accessibly
  # this will need a user_id field
  resources :users do
     resource :profile, only: [ :show ]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get "/welcome", to: 'home#welcome'
  root "home#dashboard"
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :logo

  validates_presence_of :title, :description, :logo


  has_many :messages, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  def member(user)
    group_users.find_by(user_id: user.id)
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.includes(:group_users)
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @group.group_users.create!(user: current_user)
        format.html { redirect_to root_path(current_id: @group.id), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to root_path(current_id: @group.id), notice: "Group was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.expect(group: [ :logo, :title, :description ])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul class="list-disc ml-6">
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :logo %>
    <%= form.file_field :logo, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": group.errors[:logo].none?, "border-red-400 focus:outline-red-600": group.errors[:logo].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": group.errors[:title].none?, "border-red-400 focus:outline-red-600": group.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": group.errors[:description].none?, "border-red-400 focus:outline-red-600": group.errors[:description].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "cute-btn secondary-btn" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="flex flex-row items-center justify-between p-2 bg-white border-b border-gray-200 container">
  <div class="flex items-center space-x-4 mb-4">
    <div class="flex-shrink-0">
      <%= image_tag group.logo, class: "h-16 w-16 rounded-full object-cover" if group.logo.attached? %>
    </div>

    <div class="flex flex-col">
      <h1 class="text-2xl font-bold text-gray-800">
        <%= group.title %>
      </h1>
      <p class="line-clamp-3"><%= group.description %></p>
      <p class="text-sm text-gray-500">
        <%= pluralize(group.group_users.count, 'member') %>
      </p>
    </div>
  </div>

  <div class="flex ">
    <% if group.member(current_user).present? %>
      <%= button_to "Leave Group", group_user_path(group.member(current_user)), method: :delete, class: "cute-btn secondary-btn" %>
    <% else %>
      <%= button_to "Join Group", group_group_users_path(group), method: :post, data: {turbo: false},  class: "cute-btn accent-btn" %>
    <% end %>
  </div>
</div>

app/views/groups/_group_preview.html.erb
<div class="w-full pl-1 bg-green-200" id="<%= dom_id group %>">
  <%= link_to root_path(current_id: group.id), data: {turbo_frame: "current_group"} do %>
    <div  class="w-full sm:w-auto flex items-center space-x-4 py-3 px-2 hover:bg-blue-50 bg-pink-100 group-yours-bg-accent">
      <div class="relative flex-shrink-0">
        <%= image_tag group.logo, class: "h-16 w-16 rounded-full object-cover" if group.logo.attached? %>
        <% if group.member(current_user).present? %>
          <div data-controller="notification" data-notification-count-value="<%= 1 %>" class="absolute top-0 right-0 -mt-1 -mr-1">
            <div data-notification-target="counter" class="w-5 h-5 flex items-center justify-center rounded-full text-xs font-bold text-white bg-green-500 ">
              <%= group.messages.count %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="min-w-0">
        <h3 class="text-lg font-bold truncate">
          <%= group.title %>
        </h3>
        <p class="text-gray-500 text-sm truncate">
          <%= group.description %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<% content_for :title, "Editing group" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<% content_for :title, "Groups" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Groups you have joined</h1>
    <%= link_to "New group", new_group_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="groups" class="min-w-full space-y-5 my-4">
    <% if @groups.any?%>
     <% @groups.each do |group| %>
        <div class="flex flex-col w-full sm:flex-row justify-between items-center pb-5 sm:pb-0 bg-white">
          <%= render partial: 'group_preview', object: group, as: 'group' %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No groups found.</p>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<% content_for :title, "New group" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Back to groups", groups_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<% content_for :title, "Showing group" %>
<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing group</h1>
  <%= turbo_frame_tag "group" do %>
    <%= render @group %>
  <% end %>
  <div class="mt-10">
    <%= link_to "View Messages", root_path(current_id: @group.id), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "New Message", new_group_message_path(@group), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "Edit this group", edit_group_path(@group), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "Back to groups", groups_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= button_to "Destroy this group", @group, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>