config/routes.rb
Rails.application.routes.draw do

  resources :groups, shallow: true do
    # https://guides.rubyonrails.org/routing.html
    # this defines non-shallow routes that rely on group id such as new, create, create
    # the rest like show, edit, update, destroy are defined without group id since they are persisted in DB already
    resources :messages

    # we can do a third level nesting here so that a message belongs to message and then group
    # it is frowned upon due to level of nesting
    resources :group_users, except: %i[index show update edit]
  end

  # this expects a reply action in messages as reply_message_path
  resources :messages, only: [] do
    get 'reply', on: :member
  end

  devise_for :users

  # this would be useful if only current user can view their own profile
  # this will not need a user id
  resource :profile, only: %i[edit update show]
  resolve('Profile'){[:profile]}

  # make profiles publicly accessibly
  # this will need a user_id field
  resources :users do
     resource :profile, only: [ :show ]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  get "/welcome", to: 'home#welcome'
  root "home#dashboard"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Groupable
  skip_before_action :authenticate_user!, only: :welcome
  before_action :fetch_groups, only: :dashboard

  def welcome
  end

  def dashboard

    set_current_group
  end

  private

  def set_current_group
    @current_group = Group.find_by(id: params[:current_id]).presence || @your_groups.first || @other_groups.first
    # if params[:current_id].present?

    #   if @your_groups.exists?(group.id)
    #     @current_group = group
    #   else
    #     flash.now.alert = "Request to join first."

    #     #  flash.alert = "This is shown on the next redirect too"
    #   end
    # elsif @your_groups.any?
    #   @current_group = @your_groups.first
    # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_main_content.html.erb
<!--# now do we need this to be a current_group frame? We could easily replace it with just an id an use it for turbo streams-->
<turbo-frame id="current_group" class="flex flex-col relative w-9/12 w-full h-screen bg-white">
  <!--Main content right-->
  <!--    # Here, we shall decompose our page into turbo frame components
    This will allow faster loading with parallel requests
    Also importantly, we shall defer loading of messages which can be a big speed blocker in practice-->
  <% if current_group.present? %>
    <!--Group title -->
    <!--We can add a partial to groups/show page that will give use this content-->
    <turbo-frame id="group" src="<%= group_path(current_group) %>" loading='eager'>
    </turbo-frame>
    <!--Group title-->
    <!--Then we control access to member features-->
    <% if  current_group.member(current_user).present? %>
      <div id="messages-wrapper" class="w-full bg-white px-5 py-6 pb-12 relative h-[80vh] overflow-x-hidden overflow-y-auto">
        <% if current_group&.messages&.any? %>
          <!--# since maessages will take a while to load, we can use a lazy loaded frame here-->
          <!--We can do that by fetching from the index page of messages with a group id set-->
          <turbo-frame id="messages" src="<%=  group_messages_path(current_group) %>" loading="lazy">
          </turbo-frame>
        <% else %>
          <p class="text-center ">No messages found.</p>
        <% end %>
      </div>
      <div class="absolute bottom-0 left-0 w-full">
        <turbo-frame id="new_message" src="<%= new_group_message_path(current_group) %>" loading="lazy">
        </turbo-frame>
      </div>
    <% else %>
      <div class="flex items-center h-full w-full justify-center">
        <%= content_tag :h3, "Please join first to see secret stuff", class: "text-lg text-accent" %>
      </div>
    <% end %>
  <% end %>
  <!--Main content right-->
</turbo-frame>

app/views/home/_sidebar_left.html.erb
<div class="w-3/12 h-full bg-neutral-200 pl-2 overflow-y-hidden" id="sidebar_left">
  <!--# here we can just use the groups partials-->
  <div class="py-6 flex justify-between px-4">
    <!--We can disable turbo locally and follow the whole link-->
    <%= link_to "Edit profile", edit_profile_path, data: {turbo: false}, class: "btn" %>
    <!--We set the turbo method and tell it to replace the whole page-->
    <!--supported methods are put, post and delete with get as default-->
    <!--Data turbo confirm allows use to run underlying JS confirms-->
    <%= link_to "Log out", destroy_user_session_path, class: "btn", data: { turbo_method: :delete, turbo_frame: '_top', turbo_confirm: "You want to leave?" } if user_signed_in? %>
  </div>
  <%= link_to "Create a group", new_group_path  %>
  <!--@your_groups-->
  <!--other_groups-->
  <% if your_groups.any? || other_groups.any? %>
    <h2 class="text-base my-3 text-accent ">Your groups</h2>
    <% your_groups.each do |group| %>
      <!--# here we shall broadcast events to this channel-->
      <div class="flex flex-col w-full sm:flex-row justify-between items-center pb-5 sm:pb-0 bg-white my-4">
        <%#= render partial: 'group_preview', locals: { group: group} %>
        <%= render partial: 'groups/group_preview', object: group, as: 'group' %>
        <!--            You can also pass a default variable that takes the partials name-->
        <%#= render partial: 'group_preview', object: group %>
        <!--            Access in partials as group_preview.class.is_a?(Group) == true-->
      </div>
    <% end %>
    <h2 class="text-base my-3 text-primary ">Other groups: Request to join</h2>
    <% other_groups.each do |group| %>
      <div class="flex flex-col w-full sm:flex-row justify-between items-center pb-5 sm:pb-0 bg-white my-4 ">
        <%= render partial: 'groups/group_preview', object: group, as: 'group' %>
      </div>
    <% end %>
  <% else %>
    <p class="text-center my-10">No groups found.</p>
  <% end %>
</div>

app/views/home/dashboard.html.erb
<%= turbo_stream_from "groups" %>
<div class="flex flex-row bg-gray-100 h-screen w-screen px-2 overflow-hidden" data-controller="dashboard">
  <%= render partial: 'sidebar_left', locals: { your_groups: @your_groups, other_groups: @other_groups} %>
  <%= render partial: 'main_content', locals: {current_group: @current_group} %>
</div>
<%# console %>
<!--Bare turbo stream example-->
<!--  <turbo-stream action="replace" target="current_group">
    <template>
      <div class="flex w-full h-screen bg-accent text-center justify-center text-white text-4xl">We are gone!</div>
    </template>
  </turbo-stream>-->
<!--<turbo-stream action="refresh" target="current_group"></turbo-stream>-->
<!--We can also target multiple elements-->
<!--<turbo-stream action="update" targets=".message">
  <template>
    Hello
  </template>
</turbo-stream>-->

app/views/home/welcome.html.erb
<div class="flex flex-col justify-between w-full items-center">
  <h1 class="font-bold text-4xl">This is home :)</h1>
  <div class="flex">

    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, class: "btn", data: { turbo_method: :delete, turbo_frame: '_top' } %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-default"  %>
    <% end %>

  </div>
</div>